file: /connect/excel
description: |
  Instructions for connecting from Microsoft Excel
  to BI Connector.
---
file: /connect/mysql
description: |
  Instructions for connecting from the MySQL shell to BI Connector.
---
file: /connect/tableau
description: |
  Instructions for connecting from Tableau Desktop to BI Connector.
---
file: /connect/qlik
description: |
  Instructions for connecting from Qlik Sense to BI Connector.
---
file: /connect/microstrategy
description: |
  Instructions for connecting from MicroStrategy Desktop
  to BI Connector.
---
file: /connect/excel
description: |
  Instructions for connecting from Microsoft Excel.
---
file: /connect/powerbi
description: |
  Instructions for connecting from Microsoft Power BI Desktop
  to BI Connector.
...
