# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################

from: '/reference/mongobiuser'
to: '/components'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1': {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
---
from: '/reference/mongobischema'
to: '/components'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1': {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
---
from: '/reference/mongosqld'
to: '/components'
type: 'redirect'
code: 301
outputs:
  - 'before-v1.1': {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
---
code: 301
from: '/'
to: '/master'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
from: '/tutorial/connecting'
to: '/'
type: 'redirect'
code: 301
outputs:
  - 'before-v1.1': {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
---

###
### Artifacts from the /bi-connector to /bi-connector/<branch> transition
###

code: 301
from: '/schema-configuration'
to: '/v1.1/schema-configuration'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/installation'
to: '/v1.1/installation'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/components'
to: '/v1.1/components'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/components/mongobiuser'
to: '/v1.1/components/mongobiuser'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/components/mongodrdl'
to: '/v1.1/components/mongodrdl'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/components/mongobischema'
to: '/v1.1/components/mongobischema'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/faq'
to: '/v1.1/faq'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect
---
code: 301
from: '/release-notes'
to: '/v1.1/release-notes'
outputs:
  - {'/bi-connector': 'https://docs.mongodb.com/bi-connector'}
type: redirect

...
